### ISSUE TITLE
Fix publish

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-management#30]
@nvollmar https://github.com/apache/incubator-pekko-management/actions/runs/4303600424/jobs/7503531326

Should be quite easy, need to rename https://github.com/apache/incubator-pekko-management/blob/main/.jvmopts-travis and make sure its copied into the publish step

**Comment by nvollmar** [comment]
Makes sense. Using `uses: olafurpg/setup-scala@v10` like pekko-http also works

**Comment by pjfanning** [comment]
@nvollmar olafurpg/setup-scala is no longer maintained and we are trying to migrate away from it

**Comment by nvollmar** [comment]
yep, already switched back and added a copy. Still need to fix missing credentials

**Comment by nvollmar** [comment]
working: https://github.com/apache/incubator-pekko-management/actions/runs/4341573989/jobs/7581338671
